In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for statistical data visualization
import pylab 
import scipy.stats as stats
import datetime
%matplotlib inline

pd.set_option('display.max_columns', None)

In [118]:
# ignore warnings

import warnings
warnings.filterwarnings('ignore')
replicas_copy

,dlg_id,line_n,role,text
0,0,0,client,Алло
1,0,1,manager,Алло здравствуйте
2,0,2,client,Добрый день
3,0,3,manager,Меня зовут ангелина компания диджитал бизнес з...
4,0,4,client,Ага
...,...,...,...,...
475,5,138,manager,По поводу виджетов и с ними уже обсудите конкр...
476,5,139,manager,Все я вам высылаю счет и с вами на связи если ...
477,5,140,client,Спасибо спасибо
478,5,141,client,Да да тогда созвонимся ага спасибо вам давайте
479,5,142,manager,Ну до свидания хорошего вечера

In [6]:
# load the dataset

replicas = pd.read_csv('test_data.csv')

In [8]:
# replicas

In [80]:
replicas_copy=replicas.copy()
replicas_copy

,dlg_id,line_n,role,text
0,0,0,client,Алло
1,0,1,manager,Алло здравствуйте
2,0,2,client,Добрый день
3,0,3,manager,Меня зовут ангелина компания диджитал бизнес з...
4,0,4,client,Ага
...,...,...,...,...
475,5,138,manager,По поводу виджетов и с ними уже обсудите конкр...
476,5,139,manager,Все я вам высылаю счет и с вами на связи если ...
477,5,140,client,Спасибо спасибо
478,5,141,client,Да да тогда созвонимся ага спасибо вам давайте
479,5,142,manager,Ну до свидания хорошего вечера

In [104]:
# df=replicas_copy.DataFrame()
import re
pt=r'еня\sзовут\s\w+\s'
pt2=r'меня\s\w+\sзовут'
pt3=r'компания\s\w+'
list_greeting=[]
list_introduce=[]
list_name_manager=[]
list_name_company=[]
list_goodbye=[]

for index, row in replicas_copy.iterrows():
    if row['role']=='manager' and ' здравствуйте' in row['text']  :   
        '''Pеплики с приветствием – где менеджер поздоровался'''
        list_greeting.append(row['text'])
#         print(row['role'],row['text'])

        
    if row['role']=='manager' and 'Меня зовут' in row['text']  :   
        '''Pеплики, где менеджер представил себя'''
        list_introduce.append(row['text'])
     
        
        
    if row['role']=='manager' and  re.findall(pt,row['text'])    :   
#          '''Имя менеджера'''
        a=re.findall(pt,row['text'])
        a=a[0][10:]
        list_name_manager.append(a)
#         print(a[0][10:])  

            
    if  re.findall(pt2,row['text']):
#          '''Имя менеджера'''
        b=re.findall(pt2,row['text'])
        b=b[0][5:11]
        list_name_manager.append(b)
#         print(b[0][5:11]) 
        
        
        
    if row['role']=='manager' and 'компани' in row['text']  :   
        if re.findall(pt3,row['text']):
            c=re.findall(pt3,row['text'])
            
            c=c[0][9:19]
            list_name_company.append(c)
#             print(c)

    if row['role']=='manager' and ' свидания' in row['text']  :   
        '''Pеплики где менеджер попрощался.'''
        list_goodbye.append(row['text'])    

                

list_name_company.pop(-1)

print('a. Извлекать реплики с приветствием – где менеджер поздоровался.  \n',list_greeting )

print('b. Извлекать реплики, где менеджер представил себя. \n',list_introduce)
print('c. Извлекать имя менеджера.\n',list_name_manager)
print('d. Извлекать название компании.\n',list_name_company)
print('e.Извлекать реплики, где менеджер попрощался.',list_goodbye)

a. Извлекать реплики с приветствием – где менеджер поздоровался.
 ['Алло здравствуйте', 'Алло здравствуйте', 'Алло здравствуйте']
b. Извлекать реплики, где менеджер представил себя.
 ['Меня зовут ангелина компания диджитал бизнес звоним вам по поводу продления лицензии а мы с серым у вас скоро срок заканчивается', 'Меня зовут ангелина компания диджитал бизнес звоню вам по поводу продления а мы сели обратила внимание что у вас срок заканчивается', 'Меня зовут ангелина компания диджитал бизнес звоню вам по поводу продления лицензии а мастера мы с вами сотрудничали по видео там']
c. Извлекать имя менеджера.
 ['ангелина ', 'ангелина ', 'ангелина ', 'максим']
d. Извлекать название компании.
 ['диджитал', 'диджитал', 'диджитал', 'китобизнес']
e.Извлекать реплики, где менеджер попрощался. ['Всего хорошего до свидания', 'До свидания', 'Во вторник все ну с вами да тогда до вторника до свидания', 'Ну до свидания хорошего вечера']